controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_turret_rotate
      - joint_bigarm_pitch
      - joint_forearm_pitch
      - joint_forearm_rotate
      - joint_wrist_pitch
      - joint_wrist_rotate