/gazebo_ros_control/pid_gains:
     front_left_wheel: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     front_right_wheel: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     rear_right_wheel: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     rear_left_wheel: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     shoulder_pan_joint: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     shoulder_lift_joint: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     elbow_joint: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     wrist_1_joint: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     wrist_2_joint: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
     wrist_3_joint: {p: 10.0,i: 0.01,d: 10.0,i_clamp: 0.0}
