joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
velocity_JOint_Controller:
    type: hardware_interface/VelocityJointInterface
    joint: front_left_wheel
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: front_right_wheel
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: rear_left_wheel
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: rear_right_wheel
    pid: {p: 100.0,i: 0.01,d: 10.0}

position_JOint_Controller:
    type: hardware_interface/PositionJointInterface
    joint: shoulder_pan_joint
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: shoulder_lift_joint
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: elbow_joint
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: wrist_1_joint
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: wrist_2_joint
    pid: {p: 100.0,i: 0.01,d: 10.0}
    joint: wrist_3_joint
    pid: {p: 100.0,i: 0.01,d: 10.0}
