mobot_swingarm:
  # Publish all joint states of vehicle -------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100.0
 
  # Swingarm velocity controllers -------------------------
  joint_left_swingarm_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_swingarm_left
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_right_swingarm_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_swingarm_right
    pid: {p: 100.0, i: 0.01, d: 10.0}

mobot_manipulator:
  # manipulator position controllers ----------------------
  joint_turret_rotate_controller:
    type: position_controllers/JointPositionController
    joint: joint_turret_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}



